import React from "react";
import { Col, Row } from "react-bootstrap";

const TermsofuseDetail = () => {
  return (
    <div className="container">
      <div className=" slider_col margin_bottom">
        <Row>
          <Col lg={12}>
            <div className="paymentdetail_main">
              <div className="margin_bottom">
                <h5>Instepcart Terms of Use</h5>
              </div>
              <div className="margin_bottom">
                <p className="margin_bottom">
                  This document is an electronic record in terms of Information
                  Technology Act, 2000 and rules there under as applicable and
                  the amended provisions pertaining to electronic records in
                  various statutes as amended by the Information Technology Act,
                  2000. This electronic record is generated by a computer system
                  and does not require any physical or digital signatures.
                </p>
                <p className="margin_bottom">
                  This document is published in accordance with the provisions
                  of Rule 3 (1) of the Information Technology (Intermediaries
                  guidelines) Rules, 2011 that require publishing the rules and
                  regulations, privacy policy and Terms of Use for access or
                  usage of domain name [www.Instepcart.com] (“Website”),
                  including the related mobile site and mobile application
                  (hereinafter referred to as “Platform”)
                </p>
                <p>
                  Your use of the Platform and services and tools are governed
                  by the following terms and conditions ("Terms of Use") as
                  applicable to the Platform including the applicable policies
                  which are incorporated herein by way of reference. If You
                  transact on the Platform, You shall be subject to the policies
                  that are applicable to the Platform for such transaction. By
                  mere use of the Platform, You shall be contracting with
                  Instepcart Internet Private Limited and these terms and
                  conditions including the policies constitute Your binding
                  obligations, with Instepcart.
                </p>
              </div>
              <div>
                <h5>Communications</h5>
                <p>
                  When You use the Platform or send emails or other data,
                  information or communication to us, You agree and understand
                  that You are communicating with Us through electronic records
                  and You consent to receive communications via electronic
                  records from Us periodically and as and when required. We may
                  communicate with you by email or by such other mode of
                  communication, electronic or otherwise.
                </p>
              </div>
              <div>
                <h6>Terms & Conditions:</h6>
                <ul>
                  <li>
                    Instepcart Foundation is a Section 8 company registered under
                    the Companies Act 2013.
                  </li>
                  <li>
                    The amount received as donation will be donated to NGOs and
                    similar charitable organizations working in the selected
                    thematic areas. You can visit www.Instepcartfoundation.org to
                    know more about this.
                  </li>
                  <li>The contribution, once made, will not be refunded.</li>
                  <li>
                    No certificate under section 80G of the Income Tax Act, 1961
                    will be issued.
                  </li>
                  <li>
                    By proceeding to donate, you understand and confirm that
                    this donation is not from any foreign source as defined
                    under Foreign Contribution (Regulation) Act, 2010.
                  </li>
                  <li>
                    Instepcart Foundation disclaims any and all liability and
                    assumes no responsibility whatsoever for consequences
                    resulting from any actions or inactions of the NGOs or
                    charitable organizations.
                  </li>
                  <li>
                    By proceeding to donate the money, you consent and expressly
                    waive any and all claims, rights of action and/or remedies
                    (under law or otherwise) that you may have against any of
                    the Instepcart Group entities arising out of or in connection
                    with the aforesaid transaction.
                  </li>
                  <li>
                    The donation is being collected on behalf of the Instepcart
                    Foundation and is disbursed to Instepcart Foundation. Instepcart
                    Internet Pvt Ltd disclaims all liabilities and assumes no
                    responsibility for consequences resulting from actions/
                    inactions of the Instepcart Foundation.
                  </li>
                  <li>
                    Instepcart Internet Pvt. Ltd may share your Personal
                    Identifiable Information which may include your name, phone
                    number, etc with Instepcart Foundation.
                  </li>
                </ul>
              </div>
            </div>
          </Col>
        </Row>
      </div>
    </div>
  );
};

export default TermsofuseDetail;
